### ISSUE TITLE
newbie asks ...

### ISSUE THREAD

**Issue by drogit** [NonFactors/MVC5.Grid.Web#12]
buddy ...  fantastic stuff you have here.   well done sir!

PS.  ever seen this error before?

$.fn.mvcgrid = function (options) {

vmCMGR:291 Uncaught ReferenceError: $ is not defined
    at vmCMGR:291
(anonymous) @ vmCMGR:291

vmCMGR:291 Uncaught ReferenceError: $ is not defined
    at vmCMGR:291

**Comment by Muchiachio** [comment]
It seems you didn't include `jquery.js` before `mvc-grid.js`.

**Comment by Warez-VD** [comment]
Hi,
Don't want to open new issue so I will use this one.
Is there a way to get the filtered list of the grid, after applying some filter?

**Comment by Muchiachio** [comment]
It's available on grid's interface `IGrid.Rows`.
