### ISSUE TITLE
hasDatepicker class name is not being applied to date type column

### ISSUE THREAD

**Issue by ISatByTheO** [NonFactors/MVC5.Grid.Web#13]
Hi, I recently implemented your grid into my solution and it's great but I am wondering how you are adding the hasDatepicker class name to an input.

I cannot see anywhere obvious for this to occur if you could shed some light on how it is done it would be greatly appreciated!

All the best,

**Comment by Muchiachio** [comment]
It's automatically added by jquery-ui library on initialization.

**Comment by ISatByTheO** [comment]
Have you been able to set the date format for the datepicker?

When I select a date in the datepicker it doesn't compare the values correctly, thanks

**Comment by Muchiachio** [comment]
Date picker format is controlled through client and server side localization. Grid only uses date formats set by client and server side.

**Comment by ISatByTheO** [comment]
How is this occurring then? Date equals does not work on the grid

![1](https://user-images.githubusercontent.com/7058124/29408589-b0e9165c-8340-11e7-9ad3-03178363e7e7.png)
![2](https://user-images.githubusercontent.com/7058124/29408590-b0fcd58e-8340-11e7-9251-34932bdfcd73.png)
![3](https://user-images.githubusercontent.com/7058124/29408592-b1169140-8340-11e7-96f0-d00ce284707b.png)
![4](https://user-images.githubusercontent.com/7058124/29408591-b10e1f2e-8340-11e7-9df4-94fe0195b7f9.png)

**Comment by ISatByTheO** [comment]
I'm also passing this format: {0:d'/'M'/'yy HH:mm:ss} into the Formatted method for that column

**Comment by Muchiachio** [comment]
Is your server side culture uses the same format?

**Comment by ISatByTheO** [comment]
Yeah, And I have changed it to match the datepicker (American datetime format) but it still doesn't work.

![1](https://user-images.githubusercontent.com/7058124/29410461-70063fb8-8348-11e7-9437-b4615b889e83.png)

![2](https://user-images.githubusercontent.com/7058124/29410462-70090072-8348-11e7-9543-faf84abb7ef9.png)

![3](https://user-images.githubusercontent.com/7058124/29410463-7009f126-8348-11e7-8a38-320f82ccf843.png)

![4](https://user-images.githubusercontent.com/7058124/29410464-700a12b4-8348-11e7-9a5e-cee934cd68d3.png)

**Comment by ISatByTheO** [comment]
it just returns the default list

**Comment by Muchiachio** [comment]
Could you share a small or full repro?

**Comment by ISatByTheO** [comment]
No, unfortunately, I cannot due to the nature of the application. Where does the comparison of values occur? In the Javascript?

**Comment by Muchiachio** [comment]
No it happens in mvc grid c# code.

**Comment by ISatByTheO** [comment]
Ok sure, I'll mock one up now, thanks

**Comment by ISatByTheO** [comment]
Hi Muchiachio,

Do you know if we can compare dates only?

Rather than comparing the hours/minutes/seconds as well.

Thanks

**Comment by Muchiachio** [comment]
Yes, [unregister](http://mvc-grid.azurewebsites.net/Filter/Unregister) default date equals filter and [register](http://mvc-grid.azurewebsites.net/Filter/Register) your own. The class to unregister is [DateTimeFilter](https://github.com/NonFactors/MVC5.Grid/blob/ee0b4f1da18c339016c254804f8101fd711361cd/src/Mvc.Grid.Core/Filtering/Date/DateTimeFilter.cs).

**Comment by ISatByTheO** [comment]
Hey Thanks for getting back to me on this. 

I have it like this at the moment 

MvcGrid.Filters.Register(typeof(DateTime), "Is", typeof(DateTimeFilter));

What is filter type? Will I have to do a Contains, less than etc?

**Comment by Muchiachio** [comment]
Filter type is a filter operator, so `Equals`, `GreaterThan` and so on. I think equals should be enough for comparing dates without time, unless you need all of them. I'm just not sure that your database provider will support that.

**Comment by ISatByTheO** [comment]
Nice one thank you. No I will have to have all of them. Why wouldn't my DB provider support it?

**Comment by Muchiachio** [comment]
Well you can try doing `.Where(model => model.ModificationDate.Date == filterDate)` and at least on EF and other providers I used `ModificationDate.Date` is not supported, using something like `ModificationDate.Year == filterDate.Year` and so on might work though.

**Comment by ISatByTheO** [comment]
Would that be in the Apply Method?

**Comment by ISatByTheO** [comment]
I tried to copy the DateTimeFilter straight into my own CustomDateTimeFilter but the parser doesn't work therefore value isn't initialized. Am I missing something here?

**Comment by Muchiachio** [comment]
Which parser?

**Comment by ISatByTheO** [comment]
https://github.com/NonFactors/MVC5.Grid/blob/ee0b4f1da18c339016c254804f8101fd711361cd/src/Mvc.Grid.Core/Filtering/Date/DateTimeFilter.cs

**Comment by ISatByTheO** [comment]
I know I will have to change how that works because of the fact that I will compare d/m/y but I'm just trying to glue it together so I have a better understanding of what to do.

**Comment by Muchiachio** [comment]
Oh that one, if it doesn't work then your date format is not the same as current culture one, or you just need to pass a format string.

**Comment by ISatByTheO** [comment]
Thanks. Your Unregister method seems unclear to me, in this post -> http://mvc-grid.azurewebsites.net/Filter/Unregister you have three arguments but my version of your code only takes 2. How do I unregister your DateTimeFIlter?

**Comment by Muchiachio** [comment]
Yes, 3rd parameter was removed, I will update example page.

**Comment by ISatByTheO** [comment]
Thanks. Do you have a working example of your grid working with JQuery Localization?

**Comment by Muchiachio** [comment]
I only have [this page](http://mvc-grid.azurewebsites.net/Grid/Localization) for localization.

**Comment by ISatByTheO** [comment]
I actually just got that working but thanks. So now I am at the final stage of this but before I ask this question I just want to say thanks for getting back to me so quickly! It's been a huge help.

So I have the date format and parsing working which leaves the final step. Comparing the datepicker date with our model.date. Previously in this post, you had mentioned that I should use the Linq.Where function. But I am unsure how to apply this given that I do not have the List of dates inside the Apply method. 

Can you outline how you think the comparison could be carried out? Thanks.

**Comment by Muchiachio** [comment]
Apply method is used to create an expression, which is then passed to `.Where` method by the grid itself.
You can see that from date time filter class, for example
```C#
return Expression.Equal(expression, Expression.Constant(value, expression.Type));
```
which is equivalent to
```C#
model => model.Date == value
```
which is then used inside where clause
```C#
.Where(model => model.Date == value)
```
so you have to create an expression for your date filter, so it can be reused for all dates.

**Comment by ISatByTheO** [comment]
But how do I retrieve the model.date?

**Comment by Muchiachio** [comment]
Expression is contains `model.Date` representation.

**Comment by ISatByTheO** [comment]
Sorry, this is quite confusing. How can I compare the value(BaseGridFilter) to expression in my Apply Override??

**Comment by Muchiachio** [comment]
You have to build an expression tree which does that, you can read more about them on the web.

**Comment by ISatByTheO** [comment]
So like a custom expression? Would you know of any good references?

**Comment by Muchiachio** [comment]
I used [msdn's](https://msdn.microsoft.com/en-us/library/bb882637(v=vs.110).aspx) example or any other one really, because expression code is pretty self explanatory.

**Comment by ISatByTheO** [comment]
Self-explanatory? Then how can I inform the expression in the apply method to use DateTime.Date like a can with the value being passed in? I can't find any resource or article that displays this functionality. That part does not seem Self-explanatory to me.

**Comment by Muchiachio** [comment]
It will probably be a `Expression.Property(...)`, if I recall correctly `.Date` is a property of `DateTime`.
Similarly if it would be a method, you would use `Expression.Call(...)` and it would do this
```C#
MethodInfo date = typeof(DateTime).GetMethod("Date", new Type[0]);
Expression toDate = Expression.Call(expression, date);

// toDate is now => model.CreationDate.Date()
```
You can see something similar in string filters like `StringEqualsFilter`, `StringContainsFilter`.

**Comment by ISatByTheO** [comment]
And if the model.Datetime property is Nullable can you set toDate expression correctly?

**Comment by Muchiachio** [comment]
Yes, that would be additional not null expression wrapped in an `and` expression, which would short circuit the `toDate` expression for in memory scenarios. `StringEqualsFilter` does just that by building
```C#
model => model.Value != null && model.Value.ToLower() == filter.ToLower()
```

**Comment by ISatByTheO** [comment]
But the error occurs when I pass the DateTime property Info into the Expression.Property method. 

Like so,

PropertyInfo property = typeof(DateTime).GetProperty("Date");
            
Expression toDate = Expression.Property(expression, property);

**Comment by Muchiachio** [comment]
Did you add not null expression before calling date?

**Comment by ISatByTheO** [comment]
Like Expression.NotEqual(expression, null) ?

**Comment by ISatByTheO** [comment]
PropertyInfo property = typeof(DateTime).GetProperty("Date");

            Expression notNull = Expression.NotEqual(expression, null);

            Expression toDate = Expression.Property(notNull, property);

**Comment by Muchiachio** [comment]
No you are missing an `and` expression and few other gluing pieces.
What you did now, is
```C#
// Take `.Date` property
PropertyInfo property = typeof(DateTime).GetProperty("Date");

// Create `model.CreationDate != null` expression
Expression notNull = Expression.NotEqual(expression, null);

// Create `(model.CreationDate != null).Date` property expression
Expression toDate = Expression.Property(notNull, property);
```
Here's string equals example with comments
```C#
// Takes `.ToUpper()` call 
MethodInfo toUpperMethod = typeof(String).GetMethod("ToUpper", new Type[0]);

// Creates `value.ToUpper()` expression
Expression value = Expression.Constant(Value.ToUpper());

// Creates `model.Text != null` expression
Expression notNull = Expression.NotEqual(expression, Expression.Constant(null));

// Creates `model.Text.ToUpper()` expression
Expression toUpper = Expression.Call(expression, toUpperMethod);

// Creates `model.Text.ToUpper() == value` expression
Expression equals = Expression.Equal(toUpper, value);

// Wraps everything into `model.Text != null && model.Text.ToUpper() == value` expression
return Expression.AndAlso(notNull, equals);
```

**Comment by ISatByTheO** [comment]
I have it like this

 PropertyInfo dateonly = typeof(DateTime?).GetProperty("Date");

            Expression exValue = Expression.Constant(value);

            Expression notNull = Expression.NotEqual(expression, Expression.Constant(null));

            Expression toDate = Expression.Property(notNull, dateonly);

            Expression equals = Expression.Equal(toDate, exValue);

But the toDate expression throws a null exception.

**Comment by ISatByTheO** [comment]
I also tried this,

PropertyInfo property = typeof(DateTime).GetProperty("Date");

            var filter = Expression.Constant(
                    Convert.ChangeType(value, expression.Type.GetGenericArguments()[0])
                );

            Expression typeFilter = Expression.Convert(expression, filter.Type);

            Expression toDate = Expression.Property(typeFilter, property);

Which seems to work up until the _Grid.cshtml. Then it produces this error.

The specified type member 'Date' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties.

Do you think it would be possible for me to use TruncateTime and Method info instead of PorpertyInfo and DateTime.Date?

**Comment by Muchiachio** [comment]
> The specified type member 'Date' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties.

This is thrown by the database provider not supporting a translation to SQL, as I mentioned before.
I'm not sure what `TruncateTime` is, but if it's your own function it won't be translatable to SQL.

**Comment by ISatByTheO** [comment]
Yeah fair enough. The Truncate Time is an entityfunction.

**Comment by Muchiachio** [comment]
Entity function might work, as EF has a special case for those on SQL server databases.

**Comment by Muchiachio** [comment]
Did you finish your filter?
