### ISSUE TITLE
Master Details - fluent configuration

### ISSUE THREAD

**Issue by papyr** [NonFactors/MVC5.Grid.Web#14]
Hello, great MVC control!!!

I have a question, for [master details or hierarchy grids.](http://bit.ly/2uZSqOr)

on the examples web page, I was looking for a master details sample.

How would I configure two tables with Fk keys for editing/CRUD

- Customer (Master) 
- Orders (details)

thanks

**Comment by Muchiachio** [comment]
Render two grids (details one has to be ajax one), and use `rowClicked` event on master grid to reload the details one.

**Comment by papyr** [comment]
how about a **working sample**, with a command/button on the main grids rows (like Document `Approve/Reject`)
