### ISSUE TITLE
Can't run MVC 6 grid under asp.net core

### ISSUE THREAD

**Issue by AlexSenchenko** [NonFactors/MVC5.Grid.Web#15]
Followed by installation instructions but can't see gird on a page.
Nothing rendered.
Is there any way to diagnose installation process?

**Comment by Muchiachio** [comment]
Yes, it's hard to detect sometimes as mvc core starts showing white page or no grid at all instead of throwing an error... I'm not sure how to debug that :slightly_frowning_face:

**Comment by AlexSenchenko** [comment]
Well fixed by moving views in all places where I can,
So what work for me - move views to Shared\MVCGrid\{allviews here}
You can close issue.
