### ISSUE TITLE
Date culture/format

### ISSUE THREAD

**Issue by HoloJackStones** [NonFactors/MVC5.Grid.Web#16]
Is it possible to set the date culture/format used in in the filter popup?
I need to use italian culture dd/MM/yyyy

**Comment by Muchiachio** [comment]
If you are using jQueryUI based datepicker, it can be changed with [dateFormat](https://api.jqueryui.com/datepicker/#option-dateFormat) option. Keep in mind that your server side culture has to be Italian also.

**Comment by QuuR32** [comment]
Hi there,
I'm trying to set the default dateFormat property for your mvc-grid date filter, but it seems that my action is rewritten:

`$('.hasDatepicker').datepicker({ dateFormat: 'dd/mm/yy' });`

I don't want to develop a new filter, i just want to apply this format on all your date filters input fields.
Thanks for your reply,

Quentin

**Comment by Muchiachio** [comment]
Yes, it happens because popup instances are re-rendered every time, you would have to set date picker defaults for it to work on every new instance `$.datepicker.setDefaults(options);`.

**Comment by QuuR32** [comment]
Works great! Thanks!
Awesome work by the way!

**Comment by burakilgun** [comment]
- [ ] [ ] 1. 11
- [ ] [ ] 2. 22
- [ ] [ ] 3. 33
