### ISSUE TITLE
Is it possible to display one value but sort by another?

### ISSUE THREAD

**Issue by sebasijan** [NonFactors/MVC5.Grid.Web#19]
I have a column of type `long`, which I would like to sort my items by.

However, when the grid is displayed I would rather display some string which is stored in a different property of the ViewModel.

I have tried playing around with `Formatted`, but I can't work out how to pass `model` to `Formatted` in order to display a different value (while still sorting on the original `long`)

The idea is that the items size in bytes is stored in `long`, so I want to sort on that property, but I want to display to the user a processed string to display MB/GB etc

is this possible?

**Comment by Muchiachio** [comment]
Yes, `.Add(model => model.ValueToSort).RenderedAs(model => "FormattedValues")`.
