### ISSUE TITLE
Using Export grid and multiple grids together.

### ISSUE THREAD

**Issue by danboone** [NonFactors/MVC5.Grid.Web#2]
I have been trying to figure out a way to get the export grid code to work with multiple grids on the same page.

I was thinking i would be using partial views but since the grid is being built in code represents a problem, which i can't seem to overcome, as how to call the partial views in the main view.  I keep getting Model is null errors,

I also need a custom filter and am not sure how to do it now that the grid is being generated in the code behind.

I also need and edit button on certain rows for controlling what rows can be edited.

Thank you for your assistance with this.

Dan

**Comment by Muchiachio** [comment]
You would need a view model with two grids to do that, something like this
```C#
public class IndexView
{
    public IGrid<X> FirstGrid { get; set; }
    public IGrid<Y> SecondGrid { get; set; }
}
```

Custom filters are applied through `mvcgrid` method on the client side, as long as you can select the right grid or both of them, it should work the same as with the [general example](http://mvc-grid.azurewebsites.net/Filter/Register).

You can add custom buttons using `Encoded(false)` on the [given column](http://mvc-grid.azurewebsites.net/Column/Encoding).

**Comment by danboone** [comment]
Thank you very much.  since the building of the grid is being done in the code behind this is leading to another issue, paging.
How can i instantiate the Pager in the code behind?  None of your examples demonstrate this.  I haven't been able to test the rest of your suggestions as i'm working error by error.

**Comment by Muchiachio** [comment]
It's basically the same as configuration in the view, it;s just not hidden under the html grid extensions.
```C#
grid.Pager = new GridPager<X>(grid);
grid.Pager.RowsPerPage = 15;
```

**Comment by danboone** [comment]
Thank you, I figured that out right before you posted it.  I tried to update my question before you saw it,   here is what i'm needing now.

the adding button isn't going to be on every row in the grid, I only want it on certain rows that contain a certain value in one of the fields. How can i do that in the code behind? I was going to use an actionlink to call back to the controller and open the proper page with the correct id.

**Comment by Muchiachio** [comment]
```C#
columns.Add(model => model.CanEdit ? "button" : "")
```

**Comment by danboone** [comment]
It's more complicated than that, i will try and explain what's needed a little better,

I have the following  columns in the table
grid.Columns.Add(model => model.Status).Titled("Status").Encoded(false).RenderedAs(model =>stat);            grid.Columns.Add(model => model.Error).Titled("Error");
 
The Stat is determined by the text that is in the Error Column below is the logic to determine what goes into the render, but on the export the value in the status column needs to be the status value from the data

                if (model.Error == "Unable to Retrieve Art Images")
                {
                    stat = "@Html.ActionLink('Edit', 'OpenRoeEdit', new { id = grid.RoeOpenOrderID })";
                }
                else
                {
                    stat = "< span class='label label-danger'> </span>";
                }

**Comment by danboone** [comment]
would this work?
grid.Columns.Add(model => model.Status).Titled("Status").Encoded(false)
                                        .RenderedAs(model => model.Error == "Unable to Retrieve Art Images"?
                                         "@Html.ActionLink('Edit', 'OpenRoeEdit', new { id = "+ model.RoeOpenOrderID +" })" 
                                         : "< span class='label label-danger'> </span>");

**Comment by danboone** [comment]
I have also added in the paging code as you suggested but when i run it the grid doesn't come up paged below is the code I have.

grid.Pager = new GridPager<FileErrors>(grid);
            grid.Pager.RowsPerPage = 10;

**Comment by Muchiachio** [comment]
Ye, it should work and I forgot to add pager to the processors list.
```C#
grid.Processors.Add(grid.Pager);
```

**Comment by danboone** [comment]
Thank you, I actually figured out a different way to get this working. 
Sorry I have one more thing.
I changed the design so that it is using the ajax, but now it won't page through the selections and the filtering can't be selected I think it has to do with me trying to put in a collapsible div.
could you share your mark up that you are using to generate the head of the grids as in this example?

![grid header](https://cloud.githubusercontent.com/assets/12700793/12618475/97926c2a-c4d9-11e5-9e5b-35bf27ea3f7e.PNG)



Thank you

**Comment by Muchiachio** [comment]
You can clone this repository and check out the source codes.
[Here's](https://github.com/NonFactors/MVC5.Grid.Web/blob/develop/Mvc.Grid.Web/Views/Grid/Export.cshtml) this file on web interface, or you can inspect html on the page.

**Comment by danboone** [comment]
Thank you I got it all working now, question not about grid if you happen to know.  When i published my site to our server the icons at the top of the grids disappeared and boxes are in its place.
Do you know what i missed when I deployed?

Thanks
![header](https://cloud.githubusercontent.com/assets/12700793/12646306/c63af6ee-c594-11e5-8294-5957c26ad6ad.PNG)

**Comment by Muchiachio** [comment]
Check if all your css styling is included, and double check their paths to the actual fonts.

**Comment by danboone** [comment]
thank you It was in the path in the css.
