### ISSUE TITLE
Adding Custom Partial Grid on row click

### ISSUE THREAD

**Issue by bulbul-in-a-nest** [NonFactors/MVC5.Grid.Web#20]
I have added the grid on a page in a way similar to "Grid Data Page Export" example. My question is how do I add custom partial view here. How can I include partial view name?

**Comment by Muchiachio** [comment]
If it's grid partial you want
```C#
grid.PartialViewName = "_NewPartial";
```

**Comment by bulbul-in-a-nest** [comment]
Thanks for your response, but I do not find PartialViewName property in the grid, but FooterPartialViewName is available.

To make it clear, my issue is similar to https://github.com/NonFactors/MVC6.Grid/issues/20.

But the only difference is I have constructed my grid in controller similar to the way you have done in ‘CreateExportableGrid’ of Grid data page export example.

Now on row click I want to show child/detail grid

**Comment by Muchiachio** [comment]
Sorry, its on the view `HtmlGrid` class.
