### ISSUE TITLE
Very slow loading

### ISSUE THREAD

**Issue by NathalieSpierings** [NonFactors/MVC5.Grid.Web#21]
I have multiple pages with an Url.Action to load the data for the MVCGrid.
On every page the loading of the data takes 30seconds to fill the grid. Then paging is also very slow.

I use a query handler to fill my viewmodel wich i pass to the _Grid.cshtml
In the queryhandler i query my ef6 database to retrieve the data. For organisations table i have 1400 records, and query is fast, but loading of MVCGrid takse 30seconds. Do you have any idea why this is happening?

**Comment by Muchiachio** [comment]
Did you find anything?

**Comment by NathalieSpierings** [comment]
I am still investigating. I can see that my DB Query takes 2859ms in glimpse. 
The ViewResult.ExecuteResult() takes 3028 ms.
I have 1400 records and in the _Grid i have 3 columns which i rendered as links like so:
.RenderedAs(x => Html.ActionLink
Now i changed that to     columns.Add(x => "<a href=\"/Organisatie/Overzicht/" + x.Id + "\">" + x.Naam + "</a>").Encoded(false).Titled("Naam").InitialSort(GridSortOrder.Asc);
for all the columns i wanted to render as a link.

Now the ViewResult.ExecuteResult()  takes 988.27 ms.

I cannot point my finger to it, because sometimes the grid loads in 4 seconds, sometimes it takes 12 seconds. But what i do see is that all grids with or without many records takes at least 3 or 4 seconds to render and thus visible for user.

The grid has an dropdownlist for choosing an available pagesize (5,10,25,100).
When i click the dropdownlist without choosing a page size the grid get's reloaded.
This is not always. I did not discovered yet when or why this is happening.

To me it seams like @Url.Action is causing the delay but im not sure yet

**Comment by Muchiachio** [comment]
Closing, because it doesn't look like problem is on grid's side.
