### ISSUE TITLE
How to display total number of rows in ajax grid

### ISSUE THREAD

**Issue by sebasijan** [NonFactors/MVC5.Grid.Web#23]
I would like to display the **total** number of rows above the grid somewhere, but since I can't add this in the partial how an I achieve this? Thank you

**Comment by Muchiachio** [comment]
You can use `MvcGrid/_Pager` as an example and create your own pager partial to use with 
```
.Pageable(pager => pager.PartialViewName = "_GridPagerWithTotal")
```

**Comment by sebasijan** [comment]
But even if I try

    .Pageable(pager => pager.PartialViewName = "_Pager")

Then the grid just doesn't appear, whereas it does with just

    .Pageable()

So its hard for me to understand how I can use it as an example.

Really appreciate any advice you can give

**Comment by Muchiachio** [comment]
If it doesn't appear it means that the partial crashed, strange that you don't see an exception on mvc 5.

**Comment by sebasijan** [comment]
Sorry, I should have mentioned I am using Razor Pages.

But what I mean is - _should_ the partial crash just by specifying the default `_Pager` in `Pageable()`?

**Comment by Muchiachio** [comment]
`_Pager` is not the default, unless you copied the partials differently, it's in `MvcGrid/_Pager`.

**Comment by sebasijan** [comment]
Thank you - I was using the wrong path. 

Also thanks for supporting this project it's amazing
