### ISSUE TITLE
HOWTO: Display loading background while grid is loading

### ISSUE THREAD

**Issue by ChrisMMiller** [NonFactors/MVC5.Grid.Web#25]
How do I display the loading image when the grid is refreshed. Or... where can I find documentation other than the samples?

**Comment by Muchiachio** [comment]
If you are not fond of default loading background, you can bind `reloadstart`, `reloadend` and `reloadfail` to add your own background, also make sure that `loadingDelay` is set to null, to disable the default one.

**Comment by ChrisMMiller** [comment]
I don't see the loading display the first time the grid is loaded. I see it if  I apply a filter after load but never the first time. My code is similar to the Grid Global Search example but it takes long enough to load the first time that it looks like nothing is happening momentarily.

**Comment by Muchiachio** [comment]
First one is not visible because initial grid has no content, resulting in 0 height.

**Comment by ChrisMMiller** [comment]
Thank you!

________________________________
