### ISSUE TITLE
Nested class property filter not working MVC5 NonFactor Grid

### ISSUE THREAD

**Issue by ecgdeveloper** [NonFactors/MVC5.Grid.Web#27]
I have integrated NonFactors Grid in my Mvc5 application. Its filtering not working on inner class property name however it works fine on its own properties. I have one class which is `User `and this contains `School `object onto it. This `School `class a property as `Name `and I bind it to model as below
```
columns.Add(model => model.School.Name).Titled("School Name");
columns.Add(model => model.UserName).Titled("User Name");
```
![image](https://user-images.githubusercontent.com/27555748/87224651-aea01100-c3a4-11ea-97a8-5a168b19dfa0.png)

Can you please guide how to fix it? Thank You!

**Comment by Muchiachio** [comment]
There is something else crashing, nested property nullability is [already caught and handled](https://github.com/NonFactors/MVC5.Grid/blob/v7.1.3/src/Mvc.Grid.Core/Columns/GridColumn.cs#L100) in the grid.
Does the stack trace lead anywhere?

**Comment by ecgdeveloper** [comment]
You saved me. This helped. Thank you for quick response.
