### ISSUE TITLE
Ajax grid Pagination is not working when giving the pagination outside table

### ISSUE THREAD

**Issue by Aswathims** [NonFactors/MVC5.Grid.Web#29]
I was trying to give the pagination outside the grid in order to keep it visible when we scroll the grid horizontally. It is working with normal grids. but not working with ajax grids.

**Comment by Muchiachio** [comment]
Yes, because normal one changes global browser url, while ajax is not even bound if it's outside the grid.
You will have to bind outside pager and reload the grid using the reload [api](http://mvc-grid.azurewebsites.net/Javascript/Api).
