### ISSUE TITLE
Razor notation in Custom column encoding.

### ISSUE THREAD

**Issue by danboone** [NonFactors/MVC5.Grid.Web#3]
Can i put razor notation in the encoding or am i calling it incorrectly.

Below is what i have in my code, you said in previous issue that this should work:
columns.Add(model => model.Status).Titled("Status").Encoded(false)
                        .RenderedAs(model => model.Error == "Unable to Retrieve Art Images" ?
                        "@Html.ActionLink('Edit', 'OpenRoeEdit', new { id = "+ model.RoeOpenOrderID + " })"
                        : "<span class='label label-danger'> </span>").Filterable(false);

here is the output i'm getting in the grid:
![example](https://cloud.githubusercontent.com/assets/12700793/12719462/ba4384e0-c8ba-11e5-8883-61a960f2f9f5.PNG)

Thanks

**Comment by Muchiachio** [comment]
It's C# context inside every method so you don't need to use @ at all.

**Comment by danboone** [comment]
I took out the @ and now i get an error below is my updated code and the error
 columns.Add(model => model.Status).Titled("Status").Encoded(false)
                        .RenderedAs(model => model.Error == "Unable to Retrieve Art Images" ?
                        Html.ActionLink("Edit", "OpenRoeEdit", new { id =  model.RoeOpenOrderID  })
                        : "<span class='label label-danger'> </span>").Filterable(false);

![image](https://cloud.githubusercontent.com/assets/12700793/12720436/874399a8-c8c0-11e5-9f13-f9d827a6aa46.png)

**Comment by Muchiachio** [comment]
Yes because you are essentially writing this:
```C#
public HtmlString GetValue(Model model)
{
    if (model.Error == "Unable to Retrieve Art Images")
        return new HtmlString("X"); This is not string
    else
        return " "; // <- Or this is not html string
}

**Comment by danboone** [comment]
Then how can i get this to work?
here is the whole grid
 <div class="widget-content">
            @(Html
            .Grid(Model.OpenRoeGrid)
            .Build(columns =>
            {
                columns.Add(model => model.Status).Titled("Status").Encoded(false)
                        .RenderedAs(model => model.Error == "Unable to Retrieve Art Images" ?
                        Html.ActionLink("Edit", "OpenRoeEdit", new { id =  model.RoeOpenOrderID  })
                        : "<span class='label label-danger'> </span>");
                columns.Add(model => model.Customer).Titled("Customer");
                columns.Add(model => model.Qty).Titled("Qty");
                columns.Add(model => model.Amount).Titled("Amount");
                columns.Add(model => model.PoNumber).Titled("PO Number");
                columns.Add(model => model.RequestedShipDate).Titled("Rqst Ship").Formatted("{0:d}");
                columns.Add(model => model.OrderType).Titled("Order Type");
                columns.Add(model => model.Campaign).Titled("Campaign");
                columns.Add(model => model.CampaignCount).Titled("Cmp Cnt");
                columns.Add(model => model.Error).Titled("Error");
            })
            .Pageable(pager =>
            {
                pager.RowsPerPage = 10;
            })
            .Sortable()
            )
        </div>

**Comment by Muchiachio** [comment]
Come on you can do it, this is not grid related :smile:
You just need to return same types from if statement, by either `.ToString()`ing html helper or returning empty html string on else.
```C#
columns.Add(model => model.Status).Titled("Status").Encoded(false)
.RenderedAs(model => model.Error == "Unable to Retrieve Art Images" ?
Html.ActionLink("Edit", "OpenRoeEdit", new { id = model.RoeOpenOrderID }).ToString()
: " ");
```
or
```C#
columns.Add(model => model.Status).Titled("Status").Encoded(false)
.RenderedAs(model => model.Error == "Unable to Retrieve Art Images" ?
Html.ActionLink("Edit", "OpenRoeEdit", new { id = model.RoeOpenOrderID })
: new MvcHtmlString(" "));
```

**Comment by danboone** [comment]
I didn't think that would be an optional notation.  the mark up worked thanks
