### ISSUE TITLE
Display row count

### ISSUE THREAD

**Issue by samihatuka** [NonFactors/MVC5.Grid.Web#4]
Hi,How to display the number of rows?

**Comment by Muchiachio** [comment]
Use `RowsPerPage` in `Shared/MvcGrid/_Pager.cshtml` partial view or write your custom one.
Usage in `_Pager` partial
```HTML
<div><span>@Model.RowsPerPage</span></div>
```
If you use custom partial, you will need to specify it `Pageable` options
```C#
.Pageable(pager =>
{
    pager.PartialViewName = "_MyPager.cshtml";
})
```

**Comment by samihatuka** [comment]
Thanks a lot
