### ISSUE TITLE
Try to load data urls for images

### ISSUE THREAD

**Issue by AlexSenchenko** [NonFactors/MVC5.Grid.Web#7]
Hi,
When load grid I see following:
 404 Error: 
https://domain.com/Content/MvcGrid/data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAMBAMAAACpRTGTAAAAMFBMVEUAAAD/9ISEgZGRn/82NjbGxsaHh4f/9VVVW9vb1NTU3/8ZGRkzMzMT2xyPAAAADnRSTlMAQATDTxTzOGwQqzG3KGb54LsAAABDSURBVAgdBcExDkBAEADAsahU9wO/ofJWnqKWiEIp1yqEM1NlqBKYcs5n0yaGer/Ge4unF3N8neWgKzOi9FAIXoKVH+i2E10JB20gAAAAAElFTkSuQmCC

**Comment by Muchiachio** [comment]
You can't download base64 image by appending it to your page url, you should try downloading it using just `data:image....QmCC` part and see what happens.
