### ISSUE TITLE
Grid paging not working

### ISSUE THREAD

**Issue by ktngoykalolo** [NonFactors/MVC5.Grid.Web#9]
Hello,
great tool, very simple to use. 
I have activated it but the paging is not working. 
any help ?

**Comment by Muchiachio** [comment]
Any repro steps to follow?

**Comment by ktngoykalolo** [comment]
`
        @(
        Html.Grid(Model).Build
        (

            col =>
            {
                col.Add(v => v.PhoneNumber).Titled("Phone Number").RenderedAs(v => Html.ActionLink(v.PhoneNumber, "Details", new { id = v.Id }));
                col.Add(v => v.SimIDNumber).Titled("SIM ID#");
                col.Add(s => s.Active).Titled("Active");
                col.Add(v => v.Network.NetworkName).Titled("Network").Filterable(true).Sortable(true);
            }
    ).Sortable()
    .Pageable(pager => { pager.RowsPerPage = 20; pager.PagesToDisplay = 10; })
    .Filterable()
    .Named("SIMsGrid")
    .Css("table table-hover table-bordered table-responsive table-striped")
`

**Comment by ktngoykalolo** [comment]
`  // GET: SIMCards
        public async Task<ActionResult> Index( int? operatorid)
        {


            ViewBag.OperatorID = new SelectList(db.Networks, "NetworkID", "NetworkName");

            if(operatorid != null)
            {
                var sIMCards = db.SIMCards.Include(s => s.Network).Where(s => s.OperatorID == operatorid);
                return PartialView(await sIMCards.Include(s => s.Network).OrderBy(s => s.OperatorID).ToListAsync());
            }

            
            return View(await db.SIMCards.OrderBy(s => s.SimIDNumber).ToListAsync());
        }`

**Comment by Muchiachio** [comment]
Did you initialized grid instances in javascript?

**Comment by ktngoykalolo** [comment]
```
<script>
           function InitGrid()
           {
               $('.mvc-grid').mvcgrid();
           }
           
       </script>
```

**Comment by ktngoykalolo** [comment]
fixed!!! I did not initialize the javascript properly! 👍
